// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getArticleClapCount = `-- name: GetArticleClapCount :one
SELECT COALESCE(SUM(count), 0)::int AS total_claps
FROM claps
WHERE article_id = $1
`

func (q *Queries) GetArticleClapCount(ctx context.Context, articleID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getArticleClapCount, articleID)
	var total_claps int32
	err := row.Scan(&total_claps)
	return total_claps, err
}

const getUserClapForArticle = `-- name: GetUserClapForArticle :one
SELECT COALESCE(count, 0)::int AS user_claps
FROM claps
WHERE article_id = $1 AND user_id = $2
`

type GetUserClapForArticleParams struct {
	ArticleID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetUserClapForArticle(ctx context.Context, arg GetUserClapForArticleParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserClapForArticle, arg.ArticleID, arg.UserID)
	var user_claps int32
	err := row.Scan(&user_claps)
	return user_claps, err
}

const upsertClap = `-- name: UpsertClap :one
INSERT INTO claps (article_id, user_id, count)
VALUES ($1, $2, $3)
ON CONFLICT (article_id, user_id) DO UPDATE
SET count = LEAST(claps.count + EXCLUDED.count, 50),
    updated_at = NOW()
RETURNING id, article_id, user_id, count, created_at, updated_at
`

type UpsertClapParams struct {
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Count     int32
}

func (q *Queries) UpsertClap(ctx context.Context, arg UpsertClapParams) (Clap, error) {
	row := q.db.QueryRowContext(ctx, upsertClap, arg.ArticleID, arg.UserID, arg.Count)
	var i Clap
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
