// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countCommentsByArticle = `-- name: CountCommentsByArticle :one
SELECT COUNT(*)::int FROM comments
WHERE article_id = $1
`

func (q *Queries) CountCommentsByArticle(ctx context.Context, articleID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByArticle, articleID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (article_id, user_id, body)
VALUES ($1, $2, $3)
RETURNING id, article_id, user_id, body, created_at, updated_at
`

type CreateCommentParams struct {
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Body      string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.ArticleID, arg.UserID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.article_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username AS author_username,
    u.name AS author_name,
    u.avatar_url AS author_avatar_url
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID              uuid.UUID
	ArticleID       uuid.UUID
	UserID          uuid.UUID
	Body            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AuthorUsername  sql.NullString
	AuthorName      string
	AuthorAvatarUrl string
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorUsername,
		&i.AuthorName,
		&i.AuthorAvatarUrl,
	)
	return i, err
}

const listCommentsByArticle = `-- name: ListCommentsByArticle :many
SELECT c.id, c.article_id, c.user_id, c.body, c.created_at, c.updated_at,
    u.username AS author_username,
    u.name AS author_name,
    u.avatar_url AS author_avatar_url
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.article_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type ListCommentsByArticleParams struct {
	ArticleID uuid.UUID
	Limit     int32
	Offset    int32
}

type ListCommentsByArticleRow struct {
	ID              uuid.UUID
	ArticleID       uuid.UUID
	UserID          uuid.UUID
	Body            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	AuthorUsername  sql.NullString
	AuthorName      string
	AuthorAvatarUrl string
}

func (q *Queries) ListCommentsByArticle(ctx context.Context, arg ListCommentsByArticleParams) ([]ListCommentsByArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByArticle, arg.ArticleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByArticleRow
	for rows.Next() {
		var i ListCommentsByArticleRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorUsername,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
