// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follows.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*)::int FROM follows
WHERE following_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followingID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, followingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*)::int FROM follows
WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, followerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND following_id = $2
)::bool AS is_following
`

type IsFollowingParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.username, u.name, u.avatar_url, u.bio
FROM users u
JOIN follows f ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowersParams struct {
	FollowingID uuid.UUID
	Limit       int32
	Offset      int32
}

type ListFollowersRow struct {
	ID        uuid.UUID
	Username  sql.NullString
	Name      string
	AvatarUrl string
	Bio       string
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.username, u.name, u.avatar_url, u.bio
FROM users u
JOIN follows f ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFollowingParams struct {
	FollowerID uuid.UUID
	Limit      int32
	Offset     int32
}

type ListFollowingRow struct {
	ID        uuid.UUID
	Username  sql.NullString
	Name      string
	AvatarUrl string
	Bio       string
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.AvatarUrl,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
