// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Title        string
	Body         string
	Summary      string
	ThumbnailUrl string
	Status       string
	PublishedAt  sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	SearchVector interface{}
}

type ArticleTag struct {
	ArticleID uuid.UUID
	TagID     uuid.UUID
}

type Clap struct {
	ID        uuid.UUID
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Count     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Comment struct {
	ID        uuid.UUID
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Follow struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
	CreatedAt   time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Username       sql.NullString
	Name           string
	Bio            string
	AvatarUrl      string
}
